Release 1.2.0
- uf errors out when first thing isn't a defline
- uf transparently consumes gzipped FASTA

diff --git a/uf b/uf
--- a/uf
+++ b/uf
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 #
 #  uf - Convert FASTA to unfasta format
 #  Copyright (C) 2016  Marco van Zwetselaar <io@zwets.it>
@@ -18,6 +18,9 @@
 #
 #  This utility is part of http://io.zwets.it/unfasta
 
+# Fail immediately on component failure in pipelines
+set -e -o pipefail
+
 # Function to exit this script with an error message on stderr
 err_exit() {
     echo "$(basename "$0"): $*" >&2
@@ -28,23 +31,22 @@ err_exit() {
 usage_exit() {
     echo "
 Usage: $(basename $0) [OPTIONS] [FILE ...]
-  
-  Convert FILEs to unfasta format and write to standard output.  With no
-  FILE or when FILE is '-', read standard input.  Unfasta is FASTA without
-  the pesky line breaks.
- 
-  Options
+
+  Convert FILEs to unfasta format and write to standard output.  FILE must
+  contain optionally gzipped FASTA data.  With no FILE or when FILE is '-',
+  read standard input.  Unfasta is FASTA without the pesky line breaks.
+
+  OPTIONS
    -r, --revert  Revert unfasta to FASTA (see below)
    -l, --lower   Write lowercase
    -u, --upper   Write uppercase
 
   Option -r reverts sequences to classic FASTA by breaking lines at 60 chars.
-  Note however that there is no need to do this, as every unfasta file is also
-  a valid FASTA file.  The 60 or 80 char limit is only a recommendation.
+  Note though that there is no need to do this, as every unfasta file is also
+  a valid FASTA file.  The 60 character line length is only a recommendation.
 
-  Note that all this program does is removing all white space from the sequence
-  lines in the input.  It leaves everything else intact.  Notably it performs no
-  validation on the header or data lines.  See uf-valid.
+  Apart from checking that every sequence is preceded by a header, uf performs
+  no validation of the input data.  See uf-valid.
 
   More information about the unfasta suite at http://io.zwets.it/unfasta.
 " >&2
@@ -56,6 +58,7 @@ Usage: $(basename $0) [OPTIONS] [FILE ...]
 unset REVERT
 LOWER=0
 UPPER=0
+RET=0
 
 while [ $# -ne 0 -a "$(expr "$1" : '\(.\)..*')" = "-" ]; do
     case $1 in
@@ -68,15 +71,24 @@ while [ $# -ne 0 -a "$(expr "$1" : '\(.\)..*')" = "-" ]; do
     shift || usage_exit
 done
 
-if [ -n "$REVERT" ]; then
-    gawk -bO -v WIDTH=60 -v L=$LOWER -v U=$UPPER '
-    /^>/ 
-    /^[^>]/ { for (i=1;i<=length();i+=WIDTH) { S=substr($0,i,WIDTH); print (L ? tolower(S) : U ? toupper(S) : S) } }' "$@"
-else
-    gawk -bO -v L=$LOWER -v U=$UPPER 'BEGIN { ORS="" }
-    /^>/    { if (NR!=1) print "\n"; print $0 "\n" }
-    /^[^>]/ { gsub(/[[:space:]]/,""); print (L ? tolower($0) : U ? toupper($0) : $0) }
-    END { print "\n" }' "$@"
-fi | tr -d '\r'
+[ $# -eq 0 ] && DASH="-" || DASH=""
+
+for F in $DASH "$@"; do
+    gzip -dfc "$F" |
+    if [ -n "$REVERT" ]; then
+        gawk -bO -v WIDTH=60 -v L=$LOWER -v U=$UPPER '
+        /^>/
+        /^[^>]/ { for (i=1;i<=length();i+=WIDTH) {
+           S=substr($0,i,WIDTH); print (L ? tolower(S) : U ? toupper(S) : S)
+        } }' '-'
+    else
+        gawk -bO -v L=$LOWER -v U=$UPPER 'BEGIN { ORS=""; D=0; H=0 }
+        /^>/ && D { print "\n" }
+        /^>/      { print $0 "\n"; D=0; H=1 }
+        /^[^>]/ && !H { print "uf: input is not valid FASTA\n" >"/dev/stderr"; exit 1 }
+        /^[^>]/       { gsub(/[[:space:]]/,""); print (L ? tolower($0) : U ? toupper($0) : $0); D=1 }
+        END { if (D) print "\n" }' '-'
+    fi
+done | tr -d '\r'
 
 # vim: sts=4:sw=4:et:si:ai
